title: HOOU - Program & Play
email: christian.blank@haw-hamburg.de
description: >-
  Anleitung zur Einrichtung von HOOU - Program & Play für macOS und Windows
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed